name: CI/CD Pipeline

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Upload coverage report to Code Climate
        run: |
          npx codeclimate-test-reporter < coverage/lcov.info
        env:
          CC_TEST_REPORTER_ID: ${{CC_TEST_REPORTER_ID}}
